org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.23
forge_version_range=[47.4,48)
loader_version_range=[47,)
mod_id=thewild
mod_name=TheWild
mod_license=MIT
mod_version=1.02
mod_group_id=com.rodrigo.thewild
mod_authors=Rodrigo66105
mod_description=Realistic worldwide hunting, fishing and survival for Minecraft.
mapping_channel=official
mapping_version=1.20.1
